### ISSUE TITLE
App is not functional in Nextcloud docker

### ISSUE THREAD

**Issue by seele05** [nextcloud/integration_whiteboard#11]
**Setup**:
Nextcloud21 with docker-compose on debian 64bit with upstream reverse proxy on a different server

**Steps to reproduce:**
App installed from store without errors

**What happened ?**
App is unable to use

Creation of New Whiteboards is possible (using the "+" in data view)
but trying to open results in:

_whiteboard | Spacedeck request connection error : cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9666/api/spaces
-- | --

In App Config (connected accounts?) this is shown
![image](https://user-images.githubusercontent.com/895065/108979360-de2d3080-768a-11eb-9eed-2b809a27e4c4.png)

is there a need to expose the spacedeck ports in the compose file?
or other steps to be done?

**Comment by eneiluj** [comment]
The webserver needs to be able to connect to the bundled Spacedeck server that should be running on the same container.

Could you check if the Spacedeck binary is running on the webserver container? `ps aux | grep spacedeck`
If not, there might be some error in `/.../data/appdata_XXXXXX/spacedeck/spacedeck.log`.

**Comment by seele05** [comment]
Binary is not running in the app container nor web container
spacedesk.log contains only:

> nice: can't execute './spacedeck.nexe.bin': No such file or directory

You said:
> The webserver needs to be able to connect to the bundled Spacedeck server that should be running on the same container.

which one? the webserver in the compose stack is able to communicate with the spacedesk server if running on app container
the reverse proxy should not be able to connect to the nextcloud app container directly and on web container only on the webui port?

**Comment by Weltherrscher** [comment]
Its not only from within Docker.
I run a Nextcloud 21 instance in ESXi VM under Debian 10 with nginx (and a nginx reverse proxy located within opnSense).
The Storage Space is located in a SMB share, from there, the spacedeck.nexe.bin is not executable. (bash: keine Berechtigung.)
Thus, I'm getting the same error.
If I run the executable from within /var/www.... it starts, but I'm getting the same HTTP400 error from #12

**Comment by eneiluj** [comment]
@seele05
> which one?

Spacedeck has to run on the same as the webserver. No problem on that side, this is the webserver that launches the binary.
The webserver (Php in fact) makes the requests to `http://localhost:9666`, not the reverse proxy.

> nice: can't execute './spacedeck.nexe.bin': No such file or directory

Can you check if `/.../data/appdata_XXXXXX/spacedeck/spacedeck.nexe.bin` exists? And its permissions?

@Weltherrscher Which database? The Nextcloud one or the Spacedeck one? Where do you see the locked error?

**Comment by Weltherrscher** [comment]
`[2021-02-24T17:27:39.585Z] Booting Spacedeck Open… (environment: development)
[2021-02-24T17:27:41.013Z] [redis-mock] websockets subscribed to 3 topics.
[2021-02-24T17:27:41.014Z] [redis-mock] async refresh subscribed to 4 topics.
[2021-02-24T17:27:41.016Z] Spacedeck Open listening at http://:::9666
[2021-02-24T17:27:41.022Z] createBucket null undefined
[2021-02-24T17:27:41.027Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR$
[2021-02-24T17:27:42.142Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR$
[2021-02-24T17:27:42.656Z] Executing (default): SELECT `_id`, `email`, `password_hash`, `nickname`, `avatar_original_uri`, `avatar_thumb_uri`, `confirmation_token`, `password_reset_token`, `api_token`, `home_folder_id`, `p$
[2021-02-24T17:27:43.157Z] Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: users
    at Query.formatError (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)
    at afterExecute (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at wrappedAfterExecute (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
    at replacement (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sqlite3/lib/sqlite3.js:14:21)
[2021-02-24T17:27:43.314Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR$
[2021-02-24T17:27:44.586Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR$
[2021-02-24T17:27:46.059Z] Executing (default): CREATE TABLE IF NOT EXISTS `users` (`_id` VARCHAR(255) PRIMARY KEY, `email` VARCHAR(255), `password_hash` VARCHAR(255), `nickname` VARCHAR(255), `avatar_original_uri` VARCHAR$
[2021-02-24T17:27:47.072Z] (node:1190) UnhandledPromiseRejectionWarning: SequelizeTimeoutError: SQLITE_BUSY: database is locked
    at Query.formatError (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:428:16)
    at Statement.afterExecute (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.wrappedAfterExecute (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
    at Statement.replacement (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sqlite3/lib/trace.js:19:31)
[2021-02-24T17:27:47.072Z] (node:1190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh$
[2021-02-24T17:27:47.072Z] (node:1190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero ex$
^[[0mGET /api/spaces/864efc1e-fb5e-4173-b3e6-fa6ad6c2adab ^[[0m-^[[0m - ms - -^[[0m
[2021-02-24T17:28:12.676Z] Executing (default): SELECT `_id`, `email`, `password_hash`, `nickname`, `avatar_original_uri`, `avatar_thumb_uri`, `confirmation_token`, `password_reset_token`, `api_token`, `home_folder_id`, `p$
[2021-02-24T17:28:12.679Z] Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: users
    at Query.formatError (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)
    at afterExecute (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at wrappedAfterExecute (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
    at replacement (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/node_modules/sqlite3/lib/sqlite3.js:14:21)
^[[0mPOST /api/spaces ^[[0m-^[[0m - ms - -^[[0m`

directly in /media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/spacedeck.log on the nextcloud storage space

**Comment by seele05** [comment]
Hi @eneiluj 

in the given path the file spacedeck.nexe.bin exists with the following permissions:

# ls -la spacedeck.nexe.bin
-rwx------   1 82 82 58701811 Feb 23 14:27 spacedeck.nexe.bin

**Comment by Weltherrscher** [comment]
[spacedeck.log](https://github.com/nextcloud/integration_whiteboard/files/6037845/spacedeck.log)

updated file, the above was from the manual deletion of the database.sqlite in nextcloud/appdata....

**Comment by eneiluj** [comment]
@seele05 Can you run it manually? Something like `sudo -u www-data ./spacedeck.nexe.bin` . If this works then it probably means the app tries to find the binary in the wrong place. I will tell you how to get debug information then.

@Weltherrscher Let's clean the app data and try again. Just delete `/.../data/appdata_XXXXXX/spacedeck` directory, disable the app and enable it again. It will copy the initial database (which is not empty like the one Spacedeck creates when there is none).

**Comment by seele05** [comment]
Hi @eneiluj 

from within **app** container

- #$ docker exec -it --user www-data nextcloud-app sh
- #$ ./spacedeck.nexe.bin
- #$ sh: ./spacedeck.nexe.bin: Permission denied
- #$ whoami
- #$ www-data
- #$ ls -la spacedeck.nexe.bin
- #$ -rw-r--r--    1 www-data www-data  58701811 Feb 25 08:01 spacedeck.nexe.bin

**web** container has no www-data user:

- #$docker exec -it --user www-data nextcloud-web sh
- #$unable to find user www-data: no matching entries in passwd file

as root within web container:

#$ ls -la spacedeck.nexe.bin
#$ -rw-r--r--    1 82       www-data  58701811 Feb 25 08:01 spacedeck.nexe.bin
#$ ./spacedeck.nexe.bin
# sh: ./spacedeck.nexe.bin: Permission denied
# whoami
#$ root

**Comment by Weltherrscher** [comment]
![grafik](https://user-images.githubusercontent.com/79593507/109156448-258dec80-7771-11eb-89cd-199ea2181b65.png)
Immediately after activating the app these errors pop up.
Activation fails.

**Comment by eneiluj** [comment]
@seele05 I'm not aware of which docker container has access to appdata in your context. I just know that the webserver (**not** the reverse proxy) serving Nextcloud tries to execute the binary that is in appdata (**not** in the `app/integration_whiteboard/data/spacedeck` directory, this one is copied in `appdata_xxxx/spacedeck`, that's where it's executed). If this binary is not executable because of mount options like it was for @Weltherrscher, then there is your problem.

@Weltherrscher Could you find the line corresponding to `call to a member function getContainer() on null` in nextcloud.log?
It seems the repair steps are called twice. The second time they are called, something goes wrong. Anyway if the data is copied and the binary is launched, the `getContainer()` call crash is not your problem.
Could you run `fuser /.../data/appdata_XXXXXX/spacedeck/database.sqlite`? It will show you which process is using the DB. I think all this might come from manual actions. Could you delete `appdata_xxxx/spacedeck`, then remove and delete the Whiteboard integration app in Nextcloud settings, then restart your containers, then reinstall the app and try to use it again. If this does not solve your problem, I'm clueless.

**Comment by Weltherrscher** [comment]
'
fuser database.sqlite
/media/services/NextCloud/appdata_ocu70rbh8ksw/spacedeck/database.sqlite: 28520

ps 28520
  PID TTY      STAT   TIME COMMAND
28520 ?        SNl    0:01 ./spacedeck.nexe.bin'

**Comment by seele05** [comment]
Hi @eneiluj ,

the image with the content of /var/www/html is available for both containers (app & web)
I am not questioning that the web container can execute the binary -> but for me I assume that the server seems to be ran in App container. 
BTW -> if this is the "same binary" as the standalone spacedeck container, its against the idea of docker (one server per container)

maybe I should have given in my previous answer the full paths. I checked the correct binary.

here is my compose file for maybe more insight:
likely the same as: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml

`version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=#####
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass #######

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=#######
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 8095:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
`

the volumes are on a iscsi drive mounted on docker host.
The mount points are fine. This is production like setup no testing or fun ...

**Comment by Weltherrscher** [comment]
Attached the line containing Call to a member function getContainer() on null:
(But there are many more containing this string after this first line)
`{"reqId":"5g9RMr2pbdQjiF1yqQEZ","level":3,"time":"2021-02-25T13:53:37+01:00","remoteAddr":"172.16.11.199","user":"Admin","app":"no app in context","method":"POST","url":"/settings/apps/enable","message":{"Exception":"Error","Message":"Call to a member function getContainer() on null","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":143,"function":"delegateContainerRegistrations","class":"OC\\AppFramework\\Bootstrap\\RegistrationContext","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":86,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Installer.php","line":146,"function":"runLazyRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":448,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/RegistrationContext.php","Line":405,"CustomMessage":"Error during service alias registration of comments: Call to a member function getContainer() on null"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"21.0.0.18"}`

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/issues/24711

**Comment by markuman** [comment]
> The webserver needs to be able to connect to the bundled Spacedeck server that should be running on the same container.
> 
> Could you check if the Spacedeck binary is running on the webserver container? `ps aux | grep spacedeck`
> If not, there might be some error in `/.../data/appdata_XXXXXX/spacedeck/spacedeck.log`.

That's strange here

```
root@1b90ba9af9c8:/var/www/html# ps aux | grep spacedeck
www-data    1688  0.0  0.5 923456 92144 ?        SNl  07:33   0:03 ./spacedeck.nexe.bin
root        4744  0.0  0.0   3212   872 pts/0    S+   08:38   0:00 grep spacedeck
root@1b90ba9af9c8:/var/www/html# lsof -i :9666 
root@1b90ba9af9c8:/var/www/html# 
```

I see the same error as posted first only once. I've no idea if it's running correctly now or not.

**Comment by Weltherrscher** [comment]
> [nextcloud/server#24711](https://github.com/nextcloud/server/issues/24711)

Confirm that the call errors in nextcloud.log are gone after applying that patch.
Nevertheless, the Wihteboard still doesnt run because of database locked error.

**Comment by Weltherrscher** [comment]
![grafik](https://user-images.githubusercontent.com/79593507/109294173-21bfa000-782d-11eb-90fa-99ec4bd8eb49.png)
There is a difference in spacedeck.log just before the line createBucket null undefined.
In the working instance of nextcloud, there is a database call which is not in the failing instance.
(log of failing instance is on top, just below the log of the working instance.)

**Comment by joergmschulz** [comment]
back to to original error msg: while the spacedeck.nexe.bin does exist, it is not executable.
Poking around a bit, I installed node, npm and started the .js file but that failed because of lack of the sqlite driver and issued the same error msg: does not exist. Possibly, the .bin isn't complete in all cases?

**Comment by joergmschulz** [comment]
maybe: doesn't work on alpine because a different glibc is used here?

**Comment by seele05** [comment]
After some rough experiments in my dev stage, i got the feeling that under normal circumstances the whiteboard is not able to run.
But alpine is used in spacedeck standalone and for nextcloud that should not be the problem.

Maybe someone have some time to frankenstein the spacedeck.nexe.bin in the standalone server and see what happends.

**Comment by joergmschulz** [comment]
see here https://help.nextcloud.com/t/nextcloud-21-whiteboard-error/109165/5 : really, library prerequisites???

**Comment by seele05** [comment]
no words ... okay following this I will uninstall this plugin and wait till stable release

**Comment by joergmschulz** [comment]
you've seen the experimental warning that has been added in the readme? Possibly you should just close this issue for this reason.

**Comment by szaimen** [comment]
> Possibly you should just close this issue for this reason.

This attitude doesn't help anyone! It neither helps you in getting closer to the bugs resolution nor helps the maintainer/developer figure out what the problem is.

**Comment by TheTimeWalker** [comment]
I disagree closing this issue for the warning. The warning mentions it can break on custom Nextcloud installation, however the whiteboard does not work with an unmodified official Nextcloud container, so this is still a valid issue.

**Comment by joergmschulz** [comment]
> This attitude doesn't help anyone! 
> I  disagree closing this issue for the warning. 

ok I apologize and draw bak my comment.

**Comment by seele05** [comment]
keep focused ;)

while waiting for sth. more stable for my production world, I was more playing around in my dev stage.
running standalone server and then using the plugin only for integration seems possible with not too much magic.

But I wish for more participation here or at least any feedback. 
I would love to have a rockstable whiteboard tool.

If there were a possibility to choose between "running binary from nextcloud" and "connect to exisiting server" 
not docker and docker users could happily live on

docker is one way to get ultimatively rid of all dependencies (/the missing ones) when used corretcly.

**Comment by szaimen** [comment]
Does anyone of you still use a 32-bit OS?
This could be one problem why the connection to spacedeck cannot get established as discovered here: https://help.nextcloud.com/t/nc-21-whiteboard-integration-error/109462/2

**Comment by seele05** [comment]
No x64 os on x64cpu using 64bit docker.
Root cause is definitely on Nextcloud / spacedeck side

**Comment by sutidor** [comment]
Did anyone get this working yet ?

**Comment by seele05** [comment]
unfortunately not.

**Comment by sutidor** [comment]
I made some progress.

- Install spacedeck on docker according to spacedeck/spacedeck-open repo with sqlite. (Assume the container's name is spacedeck)
- edit the config default.json
  - "host": "spacedeck",
  "endpoint": "https://**your.nextcloud.instance**/index.php/apps/integration_whiteboard/proxy",
  don't mess with the rest (including passwords), leave it as is!
- copy the database.sqlite from this repo into the spacedeck container, because it contains a user with an api token which is used to authenticate nextcloud app
- In the nextcloud app folder edit the constants:
  - www/nextcloud/apps/integration_whiteboard/lib/constants.php
  - change localhost to spacedeck
  - leave the password the same!
- Now the "check config" shows "Everything is fine!"

When I create a whiteboard the spacedeck logs look fine. On the frontend though, I get the spacedeck login page without styles, probably because of reverse proxy misconfig.

Stand by. Happy tinkering

**Comment by sutidor** [comment]
No commit since 2 months. Seems to be abandoned :(
